CREATE TABLE "RIB_SADE"."RU_AUDITORIA_DOCUMENTOS" (
	NOMBRE_DOCUMENTO VARCHAR2 (30 CHAR) NOT NULL,
	ID_DOCUMENTOS_VINCULADOS varchar2(200 CHAR) ,
	ESTADO varchar2(30 CHAR) NOT NULL,
	MENSAJE_ERROR varchar2(300 CHAR),
	FECHA DATE DEFAULT SYSDATE
	
);